config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'addresses#index'

  resources :users do
    resources :addresses
    resources :requests
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  validates :street_address, presence: true

  def self.remove_trailing_period
    # you could shorten this to self.try(:chomp, ".")
    # since you're getting ruby pretty well, I'd recommend 'Confident Ruby' by
    # Avdi Grim. It talks a lot about writing code that doesn't have to guard
    # against nil.
    self.nil? ? nil : self.chomp(".")
  end


end

app/models/request.rb
# I would pick a more descriptive name for this model (and associated controller)
# Perhaps something like ServiceRequest...
class Request < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :service_id, scope: :user_id
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :addresses
  has_many :requests

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
require 'pry'
require 'geocoder'

class AddressesController < ApplicationController

  # before any of the below address actions happen, the user will be authenticated
  before_action :authenticate_user!
  before_action :find_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = current_user.addresses
  end

  def show
  end

  def new
    if current_user.addresses.length == 0
      @welcome_message = "Thanks for signing up! Now add an address below."
    else
      @welcome_message = "Add an address"
    end
    @address = current_user.addresses.new
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      coordinates = Geocoder.coordinates(@address.street_address + ", Philadelphia, PA")
      @address.latitude = coordinates[0]
      @address.longitude = coordinates[1]
      @address.save
      redirect_to user_address_url(current_user, @address)
    else
      render :new
    end
  end

  def edit 
    @welcome_message = "Update an address"
  end

  def update
    if @address.update(address_params)
      redirect_to user_address_url(current_user, @address)
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to user_addresses_path
  end


  private

    def find_address
      @address = current_user.addresses.find(params[:id])
    end

    def address_params
      params.require(:address).permit(:street_address, :unit)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

    protected

    # I like this technique!
    def layout_by_resource
      if devise_controller?
        "devise_layout"
      else
        "application"
      end
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(user)
    '/users/:user_id/addresses/new'
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_request, only: [:show, :edit, :update, :destroy]

  def index
    @requests = current_user.requests
  end

  def show
  end

  def new
    @request = current_user.requests.new
    respond_to do |format|
      format.html
      # is a JSON response to a #new action required? I've never seen this before
      format.json {render json: @request}
    end
  end

  def create
    @request = current_user.requests.new(request_params)
    @request.save
    # if you have an HTML response for `new`, you should probably use a
    # respond_to to handle HTML / AJAX create separately as well.
    # Allow create from AJAX post request and don't refresh page
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def edit
  end

  def update
    if @request.update(request_params)
      redirect_to user_request_url(current_user, @request)
    else
      render :edit
    end
  end

  def destroy
    @request.destroy
    redirect_to user_requests_path
  end

  private

    def find_request
      @request = current_user.requests.find(params[:id])
    end

    def request_params
      params.require(:request).permit(:service_id, :notes)
    end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_address_form.html.erb
<%= form_for [current_user, @address] do |f| %> 

  <%= label_tag(:street_address, "Your address") %> 
  <%= f.text_field :street_address, :placeholder => '1234 Market St.' %>
  <%= label_tag(:unit, "Unit") %> 
  <%= f.text_field :unit, :placeholder => "301 (optional)" %> 
  <%= f.submit %>  

<% end %> 

app/views/addresses/edit.html.erb
<div class="hero">
  <div class="hero-inner">
    <div class="hero-copy">
      <h2>Edit this address</h2>  
    </div>
    <%= render 'address_form' %> 
  </div>
</div>

app/views/addresses/index.html.erb
<div class="address-container">
  <h2>Your addresses</h2>
  <ul>
    <% @addresses.each do |address| %> 
      <li><%= link_to address.street_address, user_address_path( current_user, address ) %></li>
    <% end %> 
  </ul>
  <button id="new-address"><%= link_to "Add another address", new_user_address_path( current_user ) %></button>
</div>

app/views/addresses/new.html.erb
<div class="hero">
  <div class="hero-inner">
    <div class="hero-copy">
      <h2><%= @welcome_message %></h2>  
    </div>
    <%= render 'address_form' %> 
  </div>
</div>

app/views/addresses/show.html.erb
<div id="js-parallax-window" class="parallax-window">
  <div class="parallax-static-content">
    <h1>
      <%= "#{@address.street_address}" %>
      <% if @address.unit != "" %>
        <%=", Unit #{@address.unit}" %>
      <% end %>
    </h1>
  </div>
  <div id="js-parallax-background" class="parallax-background"></div>
</div>
<div class="housing-data" data-address="<%= @address.to_JSON %>"></div> 
<div class="show-container">
  <h2>Recent 311 calls in your neighborhood</h2>
  <div class="open311-data">
  </div>
  <div class="address-tools">
    <ul class="list-centered">
      <li><%= link_to "Edit address", edit_user_address_path( current_user, @address)%></li>
      <li><%= link_to "Delete address", user_address_path( current_user, @address), method: :delete %></li>
    </ul>
    <h3><%= link_to "View my tracked requests", user_requests_path( current_user )%></h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Philly 311 Monitor</title>
  <link href='https://fonts.googleapis.com/css?family=Archivo+Black' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1><%= link_to "Philly 311 Monitor", root_path %></h1>
</header>
<%= yield %>
<footer>
  <a href="http://nabil.io" id="signature">nabil.io</a>
  <% if current_user %> 
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %> 
</footer>
</body>
</html>

app/views/layouts/devise_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Philly 311 Monitor</title>
  <link href='https://fonts.googleapis.com/css?family=Archivo+Black' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'devise_layout', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Change below if you use any custom js for devise layouts -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1><%= link_to "Philly 311 Monitor", root_path %></h1>
</header>
<div class="devise-container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/contact.html.erb
<body class="contact">
  <div class="contact-wrapper">
  <h2>Get in touch</h2>
  <p>Want to get in touch with the proper authorities about a specific service request or about 311 services in general? Contact the appropriate office below:</p>
  <ul>
    <li><a href="https://www.phillypolice.com/districts/index.html">Police</a></li>
    <li><a href="http://www.phila.gov/qualityoflife/Pages/default.aspx">Neighborhood Services</a></li>
    <li><a href="http://www.philadelphiastreets.com/customer-service/">Streets</a></li>
    <li><a href="http://www.phila.gov/li/Pages/default.aspx">Licenses and Inspections</a></li>
    <li><a href="http://www.phila.gov/parksandrecreation/Pages/default.aspx">Parks and Recreation</a></li>
  </ul> 
  <h3>About this site</h3>
  <p>This site was made by <a href="http://nabil.io">Nabil Hashmi</a> and is not associated with the City of Philadelphia's 311 services. To contribute to this project, please submit an issue or fork <a href="https://github.com/nhashmi/philly-311-monitor">the project repository</a> on GitHub.</p>
  <p class="photo-credits"><a href="https://www.flickr.com/photos/michaelrighi/2457815776/in/photolist-4KbX15-dpzeTH-7CLYiR-dmHyXj-gS4Ltj-6CFEEW-mn4Qyg-boYZPA-5YuPCg-jMQX4x-i1mdfv-ajHV5i-5m8LtA-cgHmbL-ny4WAj-7Z5eLM-2LD2Ey-dGZZ5E-2EzcNS-dHLXNE-7g3XAJ-iNrUuk-2Aa8gP-skS3YA-m7Jrjx-o8Hdv1-8vmeqC-81YV2w-mYGk1o-bbLvQ2-dmnXCg-pMkfGs-dzMwy4-bwauce-dJuMyG-ihywGQ-nKTsja-nLqE8s-octY7j-do5czr-pMkp7d-oraxb1-jgm6oz-qXhdLA-dZL9ZC-eTRq9V-5wfcyi-e6yk3t-dQEHwT-qNKMb9">The photograph of City Hall</a> used on this site was taken by Michael Righi, and <a href="https://www.flickr.com/photos/fordan/3696917154/in/photolist-6CFEEW-6SDQQa-7hWcF5-8goK32-f4LAub-6bx74a-oarw7U-MrqA-7ob9mq-f2iuma-8Sa4qi-5eMmDK-8ut8EW-8UJLE3-o5URja-csUtt1-7E4jCF-aLDCQD-cqv3QC-5i8pZa-dRSNqM-o9bfVB-6L7Jm6-qzCzxE-aSzioe-dz9qqm-bmD7f2-6RAbbC-4cqQpx-7CLYiR-7YSJ5d-7LpQhh-qAepVQ-6LiiJQ-7LjE2U-pRg7Ur-bBSekM-pctzyE-cjAyYu-92dmza-7i7Bxa-3KsjTA-n3B177-9moUut-7tjecd-rpnZsj-oHbnyu-7rYeaJ-3oRcEX-oYbp3K">the photo of the skyline</a> was taken by Bob Snyder. Both of these photos are used here under a Creative Commons 2.0 license.</p>
  </div>
</body>
</html>

app/views/requests/edit.html.erb
<div class="hero">
  <div class="hero-inner">
    <div class="hero-copy">
      <h2>Your notes on service request <%= @request.service_id %></h2>  
    </div>
    <%= form_for [current_user, @request] do |f| %> 

      <%= f.text_area :notes, size: "40x10", class: 'write-note' %> 
      <%= f.submit %>  

    <% end %> 
  </div>
</div>

app/views/requests/index.html.erb
<div class="request-container">
  <div>
    <h2>Your saved requests</h2>
    <ul>
      <% @requests.each do |request| %>
      <!-- as per my suggestion in the JS file, here's where I'd use a data tag -->
      <!-- I noticed your used them in the other views, so that's nice! -->
        <li><%= link_to "Request ID: #{request.service_id}", user_request_path( current_user, request ) %></li>
        <div class="notes">
          <p>Notes: <%= request.notes %></p>
        <button id="update-note"><%= link_to "Update note", edit_user_request_path( current_user, request )%></button>
        <button id="untrack"><%= link_to "Untrack", user_request_path( current_user, request), method: :delete %></button>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/requests/show.html.erb
<div class="hero hero-request">
  <div class="hero-inner">
    <div class="hero-copy">
      <h2>Service request <%= @request.service_id %></h2>  
      <div class="<%="specific-request request#{@request.service_id}"%>">
      </div>
      <div class="notes">
        <h4>Notes</h4>
        <p><%= @request.notes %></p>
        <span id="request-update-note"><button id="update-note"><%= link_to "Update note", edit_user_request_path( current_user, @request )%></button></span>
        <span id="request-untrack"><button id="untrack"><%= link_to "Untrack", user_request_path( current_user, @request), method: :delete %></button></span>
      </div>
    </div>
  </div>
</div>